name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "feat"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "refactor"
      - "ci"
      - "test"
      - "docs"
  - title: "⬆️ Dependencies"
    labels:
      - "dependencies"

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"

version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "feat"
  patch:
    labels:
      - "fix"
      - "bug"
      - "chore"
      - "refactor"
      - "ci"
      - "test"
      - "docs"
      - "dependencies"

template: |
  ## Changes

  $CHANGES
